[2021-10-23 23:55:03] [ INFO ] [App:40] App.main(): >>>>>> Main execution started.
[2021-10-24 00:33:33] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:36:22] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:38:37] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:39:29] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:42:08] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:42:18] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:43:47] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:45:02] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:47:00] [ INFO ] [App:44] App.main(): >>>>>> Main execution started.
[2021-10-24 00:52:07] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 00:56:30] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:09:16] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:17:16] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:18:13] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:19:12] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:28:11] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:29:10] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:52:01] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:52:56] [ ERROR] [InsertElements:53] Error con los datos del empleado: Empleado [codigo=0, apellido1=Porras, apellido2=Tete, codDepartamento=35, direccion=Calle Valbuena, fechaNacimiento=21/09/87, lugarNacimiento=Teruel, nombre=Paco, puesto=Manger, telefono=7891274]
[2021-10-24 01:54:38] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:55:30] [ ERROR] [InsertElements:53] Error con los datos del empleado: Empleado [codigo=0, apellido1=Pelaez, apellido2=Tinton, codDepartamento=35, direccion=Calle Valbuena, fechaNacimiento=23/09/87, lugarNacimiento=Teruel, nombre=Paco, puesto=Manager, telefono=34353623]
[2021-10-24 01:58:57] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 01:59:35] [ ERROR] [InsertElements:52] Error con los datos del empleado: Empleado [codigo=0, apellido1=Pepito, apellido2=Tete, codDepartamento=35, direccion=Calle Valbuena, fechaNacimiento=21/17/89, lugarNacimiento=Teruel, nombre=Paco, puesto=Manager, telefono=4325262]
[2021-10-24 02:09:08] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:09:44] [ ERROR] [InsertElements:52] Error con los datos del empleado: Empleado [codigo=0, apellido1=Pepe, apellido2=Turiel, codDepartamento=35, direccion=Calle Rio, fechaNacimiento=5482733, lugarNacimiento=Teruel, nombre=Paco, puesto=Manager, telefono=89127531]
[2021-10-24 02:12:03] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:12:30] [ ERROR] [HibernateUtil:31] HibernateUtil.buildSessionFactory(): Initial SessionFactory creation failed.
org.hibernate.DuplicateMappingException: The [Empleado] and [ejercicio.entities.Empleado] entities share the same JPA entity name: [Empleado] which is not allowed!
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.addEntityBinding(InFlightMetadataCollectorImpl.java:313)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:825)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at ejercicio.utils.HibernateUtil.buildSessionFactory(HibernateUtil.java:26)
	at ejercicio.utils.HibernateUtil.<clinit>(HibernateUtil.java:17)
	at ejercicio.service.InsertElements.insertarEmpleado(InsertElements.java:30)
	at ejercicio.principal.App.main(App.java:74)
[2021-10-24 02:15:24] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:15:43] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:16:00] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:16:36] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:16:49] [ ERROR] [InsertElements:68] Error al acceder a la BDjava.lang.NullPointerException
[2021-10-24 02:16:49] [ ERROR] [InsertElements:51] El codigo no existe en la base de datos 4
[2021-10-24 02:17:15] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:18:00] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:18:07] [ ERROR] [App:37] Dato para el codigo no validojava.util.Scanner[delimiters=\p{javaWhitespace}+][position=0][match valid=false][need input=false][source closed=false][skipped=false][group separator=\,][decimal separator=\.][positive prefix=][negative prefix=\Q-\E][positive suffix=][negative suffix=][NaN string=\Q�\E][infinity string=\Q∞\E]
[2021-10-24 02:19:12] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:21:11] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
[2021-10-24 02:31:17] [ INFO ] [App:46] App.main(): >>>>>> Main execution started.
